services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile

  backend:
    depends_on:
      - frontend
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3000:80"