services:
  frontend:
    build:
      context: ../app
      dockerfile: Dockerfile

  backend:
    depends_on:
      - frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"